name = "stefanuk12/aimwork"
description = "The library for any Roblox aiming scripts."
version = "0.1.0"
authors = ["Stefanuk12"]
license = "MIT"
includes = [
    "pesde.toml",
    "README.md",
    "LICENSE",
    "src/*"
]

[target]
environment = "roblox"
bin = "src/main.luau"
lib = "src/init.luau"
build_files = ["src"]

[indices]
default = "https://github.com/pesde-pkg/index"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[dev_dependencies]
darklua = { repo = "Stefanuk12/darklua", rev = "90d682b16d3e130d93b405b05f0515b32dae1659", target = "lune" }
stylua = { name = "pesde/stylua", version = "^2.0.1", target = "lune" }
luau_lsp = { name = "pesde/luau_lsp", version = "^1.39.2", target = "lune" }
selene = { name = "pesde/selene", version = "^0.27.1", target = "lune" }

[dependencies]
trove = { wally = "wally#sleitnick/trove", version = "^1.5.0" }
