name: Check

on:
  workflow_call:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  code-style:
    name: Verify code style and quality
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Pesde
        uses: lumin-org/setup-pesde@v0.3.1
        env:
          GH_TOKEN: ${{ github.token }}
        with:
          cache: true

      - name: Refresh Shell
        run: export PATH="$PATH:~/.pesde/bin" && source ~/.bashrc

      - name: Install Pesde Dependencies
        run: pesde install

      - name: StyLua
        run: stylua --color always --check src

      - name: Download Luau Types
        run: curl -s https://raw.githubusercontent.com/JohnnyMorganz/luau-lsp/main/scripts/globalTypes.d.lua > globalTypes.d.lua

      - name: Luau Analyze
        run: |
          set -e
          output=$(luau_lsp analyze --settings .vscode/settings.json --definitions=globalTypes.d.lua src)
          if [ -n "$(echo "$output" | grep -v '^\s*$')" ]; then
            echo "Luau Analyze found issues:"
            echo "$output"
            exit 1
          fi

      - name: Selene
        run: selene -q src
